#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[stronglifters::default]
      - recipe[stronglifters::capistrano]
      - recipe[stronglifters::delayed_job]
      - recipe[stronglifters::nginx]
      - recipe[stronglifters::unicorn]
      - recipe[stronglifters::nodejs]
      - recipe[stronglifters::rbenv]
      - recipe[stronglifters::postgres]
    attributes:
      postgres:
        database: "mydb"
        host: "localhost"
        username: "rails"
      postgresql:
        password:
          postgres: 'password'
      rbenv:
        ruby_version: '2.2.2'
  - name: web
    run_list:
      - recipe[stronglifters::default]
      - recipe[stronglifters::rails]
    attributes:
      rbenv:
        ruby_version: '2.2.2'
      user:
        username: 'rails'
      aws:
        username: 'rails'
      capistrano:
        root_path: '/var/www/app'
        username: 'rails'
        env:
          app_api_key: 'api-key'
          app_secret_key: 'secret-key'
      nginx:
        domain: 'www.example.com'
      puma:
        username: 'rails'
        current_path: '/var/www/app/current'
      postgres:
        database: "mydb"
        username: "rails"
        password: "password"
        host: "localhost"

transport:
  name: sftp
